### PR TITLE
format code with `prettier`

### PR DESCRIPTION
**Pull request by altkdf**
Also adds a workflow for checking that formatting is still correct.

### CODE REVIEW

**Comment by altkdf** [comment]
Format check works: https://github.com/dfinity/motoko-bitcoin/actions/runs/10901157062/job/30250344692.

**Comment by altkdf** [comment]
It would also be useful to add an automatic check for compiler warnings, but I didn't find anything of that kind in `mops`.

**Comment by altkdf** [comment]
After this PR, we should be ready to publish this crate on [mops.one](https://mops.one/).

**Comment by altkdf** [comment]
@fspreiss please take a look at the description of https://github.com/dfinity/motoko-bitcoin/pull/5/commits/196ce65009bdc4144240474faed8d469d16b19ef. This should reduce the time needed to review this PR by 99%.

**Review by fspreiss — APPROVED** [review]
Thanks, @altkdf!

**Pull request merged**
